Added new command in zshrc: - tcopy / tpaste - ssh_mutli - rssh - mssh - lh

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -110,4 +110,288 @@ else
 fi
 }
 
+ssh_load_identities() {
+  if [ "($uname -s)" == "Darwin" ]; then
+    SSH_ADD_OPT="-K -A"
+  fi
+
+  ssh-add -L > /dev/null 2>&1
+  [ $? -ne 0 ] && ssh-add $SSH_ADD_OPT > /dev/null 2>&1
+}
+
+update_ssh_auth_sock() {
+  if [ -z $SSH_AUTH_SOCK ] || [ ! -e $SSH_AUTH_SOCK ]; then
+    export SSH_AUTH_SOCK=$(find /tmp/ -path "*/ssh-*" -name "agent.*" -uid $(id -u) 2>/dev/null | head -n 1)
+  fi
+}
+
+
+alias ssh='ssh_load_identities ; update_ssh_auth_sock ; ssh'
+
+rssh() {
+  if [ $# -ne 1 ]; then
+    echo "Usage: rssh SERVER"
+    echo "Open ssh session in another tmux window"
+    return 1
+  fi
+  if [ "$TERM" != "screen" ]; then
+    echo "Not in a tmux session"
+    return 1
+  fi
+
+  CMD='export SSH_AUTH_SOCK=$(find /tmp/ -path "*/ssh-*" -name "agent.*" -uid $(id -u) 2>/dev/null | head)'
+  SERVER=$1
+  tmux new-window "eval $CMD; ssh $SERVER"
+}
+
+ssh_multi() {
+  if [ "$TERM" != "screen" ]; then
+    echo "Not in a tmux session"
+    return 1
+  fi
+
+  SSH_USER=$USER
+
+  # Get arguments
+  OPTS=$(getopt -o lh: -n "ssh_multi" -- "$@")
+  eval set -- "$OPTS"
+  while true; do
+    case "$1" in
+    -h) echo 'Usage:
+   echo $SERVERS_LIST | ssh_multi
+   ssh_multi $SEVERS_LIST'
+     shift
+     ;;
+    -l) SSH_USER=$2 ; shift 2 ;;
+    --) shift ; break ;;
+    *) echo "Internal error!" ; return ;;
+    esac
+  done
+
+  HOSTS_LIST=""
+  if read -t 0.1 line; then
+    HOSTS_LIST=$line
+    while read -t 0.1 line; do
+      HOSTS_LIST="$HOSTS_LIST $line"
+    done
+  else
+    HOSTS_LIST="$@"
+  fi
+
+  HOSTS_LIST=$(echo $HOSTS_LIST | tr '[\r\n\t ]+' ' ' | sed -E 's/(^ +| +$)//g' | sed -E 's/ +/ /g')
+
+  if [ -z "$HOSTS_LIST" ]; then
+      echo "No host was provided."
+      echo 'Usage:
+   echo $SERVERS_LIST | ssh_multi
+   ssh_multi $SEVERS_LIST'
+      return
+  fi
+
+  NB=0
+  CMD='export SSH_AUTH_SOCK=$(find /tmp/ -path "*/ssh-*" -name "agent.*" -uid $(id -u) 2>/dev/null | head)'
+  IFS=$' '
+  for SERVER in $(echo $HOSTS_LIST); do
+    if [ $NB -eq 0 ]; then
+      tmux new-window "eval $(echo $CMD); ssh -l $SSH_USER $SERVER"
+    else
+      tmux split-window -h "eval $(echo $CMD); ssh -l $SSH_USER $SERVER"
+      tmux select-layout tiled > /dev/null
+    fi
+    NB=$((NB+1))
+  done
+  tmux select-pane -t 0
+  tmux set-option synchronize-panes on
+}
+
+tpaste() {
+  if [ "x$1" = "x-h" ] || [ "x$1" = "x--help" ]; then
+    echo "Usage:
+  tpaste > FILENAME
+  tpaste FILENAME
+  echo \$DATA | tpaste
+  echo \$DATA | tpaste FILENAME"
+    return 1
+  fi
+
+  if [ $# -eq 1 ]; then
+    if [ -f $1 ]; then
+      echo "File $1 already exist. Do you want to overwrite it? (y/n)"
+      read A
+      if [ "x$A" != "xy" ]; then
+        return 0
+      fi
+    fi
+    OUT=$1
+  else
+    OUT=/dev/stdout
+  fi
+
+  # Get BASE64 CMD
+  case $(uname -s) in
+    Darwin) BASE64_OPT="-D" ;;
+    *) BASE64_OPT="-d" ;;
+  esac
+
+
+  # Check if input from stdin
+  if ! read -t 0.1 LINE; then
+    echo "Paste your base64 text here and finish with single '.' on one line:"
+    LINE=""
+    TEXT=""
+    while true; do
+      read LINE
+      if [ "x$LINE" = "x." ]; then
+        break
+      fi
+      TEXT="${TEXT}${LINE}"
+    done
+  else
+    TEXT=$LINE;
+    while read -t 0.1 LINE; do
+      TEXT="${TEXT}${LINE}"
+    done
+  fi
+
+  echo $TEXT | base64 $BASE64_OPT | gunzip -c >! $OUT
+}
+
+tcopy() {
+
+  if [ "x$1" = "x-h" ] || [ "x$1" = "x--help" ]; then
+    echo "Usage:
+  tcopy FILENAME
+  cat FILENAME | tcopy"
+    return 1
+  fi
+
+  # Test if we got input from stdin or a filename
+  if ! read -t 0.1 FIRST_LINE; then
+    # If no input from stdin, test if there is a filename given as argument
+    if [ $# -ne 1 ]; then
+      # If not, show usage
+      echo "Usage:
+  tcopy FILENAME
+  cat FILENAME | tcopy"
+      return 1
+    else
+      # If yes, check if file exists
+      FILE=$1
+
+      if [ ! -f $FILE ]; then
+        echo "File $FILE does not exists"
+        return 1
+      fi
+      MODE="FILENAME"
+    fi
+  else
+    MODE="STDIN"
+  fi
+
+  # Get terminal width
+  WIDTH=$(tput cols)
+  if [ $WIDTH -lt 20 ]; then
+    echo "Your terminal width is too low (<30 columns)"
+    return 1
+  fi
+
+  # Get BASE64 CMD
+  case $(uname -s) in
+    Darwin) BASE64_CMD="base64 -b0" ;;
+    *) BASE64_CMD="base64 -w0" ;;
+  esac
+
+  if [[ "$MODE" == "STDIN" ]]; then
+    # Store input in a temp file
+    TCOPY_TEMP_FILE=$(mktemp /tmp/tcopy.XXXXX)
+    echo $FIRST_LINE >> $TCOPY_TEMP_FILE
+
+    while read -t 0.1 LINE; do
+      echo $LINE >> $TCOPY_TEMP_FILE
+    done
+    FILE=$TCOPY_TEMP_FILE
+  fi
+
+  #Check size of file
+  SIZE=$(stat -f %z $FILE)
+  if [ $SIZE -gt 20000 ]; then
+    echo "Warning. Data size is $SIZE. Are you sure you want to copy on terminal? (y/n)"
+    read A
+    if [ "x$A" != "xy" ]; then
+      # Remove temp file if any
+      [[ ! -z $TCOPY_TEMP_FILE ]] && [[ -f $TCOPY_TEMP_FILE ]] && rm -f $TCOPY_TEMP_FILE
+      return 0
+    fi
+  fi
+
+  CMD="cat \"$FILE\" | gzip -c | $BASE64_CMD"
+  eval $CMD
+
+  # Remove temp file if any
+  [[ ! -z $TCOPY_TEMP_FILE ]] && [[ -f $TCOPY_TEMP_FILE ]] && rm -f $TCOPY_TEMP_FILE
+
+}
+
+
+start_tmux() {
+  TMUX_SOCK_PATH="/tmp/tmux-$(id -u)/default"
+  if [ -S $TMUX_SOCK_PATH ]; then
+    TMUX_SOCK="-S $TMUX_SOCK_PATH"
+  fi
+
+  # Start tmux if not already in a tmux/screen session
+  if [ "$TERM" != "screen" ]; then
+    # Start tmux
+    if which tmux > /dev/null 2>&1; then
+      #if not inside a tmux session, and if no session is started, start a new session
+      (tmux attach || tmux new-session)
+    fi
+  fi
+}
+
+lh() {
+  if ! which llh > /dev/null 2>&1; then
+    echo "llh command not found."
+    return 1
+  fi
+
+  FILTER=$1
+  IFS=$'\r\n'
+  for line in $(llh $FILTER); do
+    SERVER=$(echo $line | awk '{print $2}')
+    echo -n "$SERVER "
+  done
+  echo
+}
+
+mssh() {
+  HOSTS_LIST=""
+  while read line; do
+    HOSTS_LIST="$HOSTS_LIST $line"
+  done
+  HOSTS_LIST=$(echo $HOSTS_LIST | tr '[\r\n\t ]+' ' ' | sed -E 's/(^ +| +$)//g' | sed -E 's/ +/ /g')
+
+  #echo "HOSTS_LIST=$HOSTS_LIST"
+
+  if [ -z "$HOSTS_LIST" ]; then
+    echo "No host was provided."
+    echo "Usage:"
+    echo '  echo $LIST_OF_HOSTS" | mssh CMD'
+    return 1
+  fi
+
+  IFS=$' '
+  for SERVER in $(echo $HOSTS_LIST); do
+    echo -e "\033[32m[$SERVER]\033[0m"
+    ssh $SERVER "$@"
+  done
+
+}
+
+
 [ -f ~/.zshrc.local ] && . ~/.zshrc.local
+
+if [[ $START_TMUX -eq 1 ]]; then
+  start_tmux
+fi
+
